### PR TITLE
Fix opening sensitive data docs page

### LINKED ISSUE #505: Can't open the page "Sensitive data"
### Type of Documentation Issue

Broken link

### Documentation Page

https://docs.browser-use.com/customize/sensitive-data

### Issue Description

https://github.com/user-attachments/assets/966f60a9-b97d-4135-9aaf-eef2fc180efc

I click on the navigation item but nothing happens.

### Suggested Changes

Fix the link.

### PR DESCRIPTION
**Pull request by nilsreichardt**
The issue was that the docs file was named `sensitive_data.mdx` instead of `sensitive-data.mdx`. I renamed the file and this fixed it.

image

Fixes #505 
Bug caused in #503

### CODE REVIEW

**Comment by Rajeev-SG** [comment]
Hey guys, this is a great project, I am trying it out for the first time today. I just got a funny error: Agent.__init__() got an unexpected keyword argument 'sensitive_data'

I think you may have published the documentation page before the pip package was updated and released with the sensitive data handling functionality.

When I ran pip index versions browser-use, I got this: WARNING:
browser-use (0.1.32)
Available versions: 0.1.32, 0.1.31, 0.1.30, 0.1.29, 0.1.28, 0.1.27, 0.1.26, 0.1.25, 0.1.24, 0.1.23, 0.1.22, 0.1.20, 0.1.19, 0.1.18, 0.1.17, 0.1.16, 0.1.15, 0.1.14, 0.1.13, 0.1.12, 0.1.11, 0.1.10, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.1, 0.1.0
  INSTALLED: 0.1.32
  LATEST:    0.1.32

I assume the sensitive data handling features are not in 0.1.32. will you be releasing a new version soon? Thanks!
