### ISSUE TITLE
Unexpected keyword argument 'browser_binary_path'

### ISSUE THREAD

**Issue by DesiKeki** [browser-use/browser-use#1541]
### Bug Description

Hi All,

I am trying to run browser-use with my real browser which can access to a personal google sheet. I have closed all running Chrome instances and given path to my chrome executable.

But doing so is giving me TypeError: BrowserConfig.__init__() got an unexpected keyword argument 'browser_binary_path'

Please let me know if I am missing something here or suggest a fix for this.

### Reproduction Steps

Install browser-use in Windows 11
Close all Chrome instances
Try running browser-use to connect to your browser.

### Code Sample

```python
from browser_use import Agent, Browser, BrowserConfig
from langchain_anthropic import ChatAnthropic
import asyncio, os

# Configure the browser to connect to your Chrome instance
browser = Browser(
    config=BrowserConfig(
        # Specify the path to your Chrome executable
        browser_binary_path='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    )
)

# Create the agent with your configured browser
agent = Agent(
    task="""
            Open this google sheet: https://docs.google.com/spreadsheets/d/15FpkG1omz9my-X6HHG-a8oorwo3qGodhpRGjEE-pPgw/edit
            And enter following data in different rows:
            Capital and population of following countries:
            India
            China
            USA
        """,
    llm=ChatAnthropic(model='claude-3-5-haiku-20241022'),
    browser=browser,
)

async def main():
    await agent.run()

    input('Press Enter to close the browser...')
    await browser.close()

if __name__ == '__main__':
    asyncio.run(main())
```

### Version

0.1.40

### LLM Model

Claude 3.5 Haiku

### Operating System

Windows 11

### Relevant Log Output

```shell
INFO     [browser_use] BrowserUse logging setup complete with level info
INFO     [root] Anonymized telemetry enabled. See https://docs.browser-use.com/development/telemetry for more information.
Traceback (most recent call last):
  File "C:\Users\Vi2883\native_browser_session.py", line 9, in <module>
    config=BrowserConfig(
           ^^^^^^^^^^^^^^
TypeError: BrowserConfig.__init__() got an unexpected keyword argument 'browser_binary_path'
```

**Comment by dharam1291** [comment]
Update the version to either 0.1.41 or 42

**Comment by DesiKeki** [comment]
> Update the version to either 0.1.41 or 42

Worked with 0.1.42
Thanks a lot @dharam1291
